---
jobs:
- name: Build
  public: true
  serial: true
#  serial_groups: ["build"]
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: ci
      trigger: false
    - get: version
      trigger: false
      params: {bump: patch, pre: rc}
  - task: build-task
    file: ci/task_build.yml
- name: Deploy
  public: true
  serial: true
#  serial_groups: ["build"]
  plan:
  - aggregate:
#    - get: source-code
#      trigger: true
#      passed: [Build]
    - get: ci
      trigger: false
      passed: [Build]
    - get: version
      trigger: false
      passed: [Build]
  - task: Deploy123
    config:
       inputs:
         - name: quotes-build
           path: .
         - name: accounts-build
           path: .
         - name: version
       run:
         path: find
         args: ["."]
  - aggregate:
    - put: deploy-to-cf
      params:
        manifest: resource-web-app/manifest.yml
        path: resource-web-app
        environment_variables:
          CF_TARGET: {{cf-api}}

  - put: version
    params: {file: version/number}

resources:
- name: source-code
  type: git
  source:
    uri: {{code-repo}}
    branch: {{code-branch}}

- name: ci
  type: git
  source:
    uri:  {{ci-repo}}
    branch: master

- name: version
  type: semver
  source:
    driver: git
    uri: {{ci-repo-git}}
    branch: {{version-branch}}
    file: {{app-version-file}}
    private_key: {{springboottrader-ci-repo-private-key}}

- name: deploy-to-cf
  type: cf
  source:
     api: {{cf-api}}
     username: {{cf-username}}
     password: {{cf-password}}
     organization: {{cf-organisation}}
     space: {{cf-space}}
     skip_cert_check: {{cf-skip-ssl}}
