---
jobs:
- name: Build
  public: true
  serial: true
  plan:
  - aggregate:
    - get: SpringBootTrader-development
      trigger: true
    - get: SpringBootTrader-ci
      trigger: false
    - get: version
      trigger: false
      params: {bump: patch}
  - task: build
    file: SpringBootTrader-ci/task_build.yml
  - put: version
    params: {file: version/number}

resources:
- name: SpringBootTrader-development
  type: git
  source:
    uri: https://github.com/dpinto-pivotal/cf-SpringBootTrader.git
    branch: development

- name: SpringBootTrader-ci
  type: git
  source:
    uri: https://github.com/dpinto-pivotal/SpringBootTrader-ci.git
    branch: master

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:dpinto-pivotal/SpringBootTrader-ci.git
    branch: version
    file: version
    private_key: {{springboottrader-ci-repo-private-key}}
