---
jobs:
- name: Build
  public: true
  serial: true
  serial_groups: ["build"]
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: ci
      trigger: false
    - get: version
      trigger: false
      params: {bump: patch}
  - task: build-task
    file: SpringBootTrader-ci/task_build.yml
  - put: version
    params: {file: version/number}
- name: Deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: source-code
      trigger: true
      passed: [Build]
  - task: deploy-task
    config:
      run:
        path: ls
        args: ["-lrt"]
resources:
- name: source-code
  type: git
  source:
    uri: {{code-repo}}
    branch: {{code-branch}}

- name: ci
  type: git
  source:
    uri:  {{ci-repo}}
    branch: master

- name: version
  type: semver
  source:
    driver: git
    uri: {{ci-repo-git}}
    branch: {{version-branch}}
    file: {{app-version-file}}
    private_key: {{springboottrader-ci-repo-private-key}}
