---
jobs:
- name: Build
  public: true
  serial: true
  plan:
  - aggregate:
    - get: SpringBootTrader-development
      trigger: true
    - get: SpringBootTrader-ci
      trigger: false
    - get: version
      trigger: false
      params: {bump: patch}
  - task: build
    file: SpringBootTrader-ci/task_build.yml
  - put: version
    params: {file: version/number}

resources:
- name: SpringBootTrader-development
  type: git
  source:
    uri: {{trader-repo}}
    branch: development

- name: SpringBootTrader-ci
  type: git
  source:
    uri:  {{trader-ci-repo}}
    branch: master

- name: version
  type: semver
  source:
    driver: git
    uri: {{trader-ci-repo-git}}
    branch: {{version-branch}}
    file: {{app-version-file}}
    private_key: {{springboottrader-ci-repo-private-key}}
